
import Home from "@/components/home";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomePage() {
  return <Home/>
}